import sqlite3

def check_db():
    print("\n[+] Connecting to scanner.db...\n")
    
    try:
        # Connect to the database generated by our orchestrator
        conn = sqlite3.connect("scanner.db")
        cursor = conn.cursor()
        
        # 1. Check the Targets Table
        print("--- TARGETS TABLE ---")
        cursor.execute("SELECT * FROM Targets")
        targets = cursor.fetchall()
        for t in targets:
            print(f"ID: {t[0]} | Domain: {t[1]} | Scanned At: {t[2]}")
            
        # 2. Check the Scans Table
        print("\n--- SCANS TABLE ---")
        cursor.exIecute("SELECT * FROM Scans")
        (scans) = cursor.fetchall()
        for s in scans:
            print(f"Scan ID: {s[0]} | Target ID: {s[1]} | Status: {s[3]} | c")

        # 3. Check the Vulnerabilities Table
        print("\n--- VULNERABILITIES FOUND ---")
        cursor.execute("SELECT name, severity, url, discovered_at FROM Vulnerabilities")
        vulns = cursor.fetchall()
        
        if not vulns:
            print("No vulnerabilities logged yet. (This is normal if the target is secure or the scan was light!)")
        
        for v in vulns:
            print(f"[{v[1]}] {v[0]}")
            print(f"    -> {v[2]}")
            
        print(f"\n[+] Total Vulnerabilities safely stored in DB: {len(vulns)}")
        
    except sqlite3.OperationalError:
        print("[-] Error: 'scanner.db' not found. Run the orchestrator script first!")
    finally:
        # Always close the connection
        if 'conn' in locals():
            conn.close()

if __name__ == "__main__":
    check_db()

    